reference:
    /home/tilman/storage/ref_gg6a/GCF_000002315.5_GRCg6a_genomic.fna.gz
Data_Folder:
    /home/tilman/scripts/genotype_low_coverage/testfiles

founders:
    /home/tilman/storage/all_GQ20_MQ50_noIndels_callrate0.3.vcf    

bcftools:
    /home/tilman/miniconda3/envs/v3/bin/bcftools    

